### ISSUE TITLE
No realtime data

### ISSUE THREAD

**Issue by BCI1999** [hyperrail/hyperrail-for-android#120]
Using the latest version (1.3.2) there seems to be an issue fetching the realtime data (delays, track changes etc.). 
The official app seems to somewhat be able to display this data.
I suppose this is an issue on NMBS' end, or did the API change completely?

**Comment by Bertware** [comment]
This is either an issue on the NMBS side, or a change in their data flows. It seems realtime data is no longer passed on to the old app

**Comment by Bertware** [comment]
See also https://github.com/iRail/iRail/issues/459

**Comment by BCI1999** [comment]
Thanks for the quick update!
Hopefully it's just the NMBS' incompetence and it'll magically work again soon
