### ISSUE TITLE
Sharing arrival or departure are switched

### ISSUE THREAD

**Issue by kuylensa** [hyperrail/hyperrail-for-android#93]
When you share you're departure-time, then the text shows the arrival-time.
And vice versa.

On top of that is the time not shown in 24h-format, but in 12h-format without the notion of a.m. or p.m.. This can be confusing.

**Comment by Bertware** [comment]
Wrong casing caused the time to be in 12h format, this has been fixed. Apparently I mixed up the translations for the share departure/arrival buttons, this has been fixed now and will be included in the next update. Thanks for reporting this issue!
